config/routes.rb
Rails.application.routes.draw do

  # Routes for the Post resource:

  # Writing some test code

  # CREATE
  post("/insert_post", { :controller => "posts", :action => "create" })
          
  # READ
  get("/posts", { :controller => "posts", :action => "index" })
  
  get("/posts/:path_id", { :controller => "posts", :action => "show" })
  
  # UPDATE
  
  post("/modify_post/:path_id", { :controller => "posts", :action => "update" })
  
  # DELETE
  get("/delete_post/:path_id", { :controller => "posts", :action => "destroy" })

  #------------------------------

  # Homepage
    get("/",{ :controller => "application", :action => "writing_index" })

  # Writing
    get("/writing",{ :controller => "application", :action => "writing_index" })
  
  # Writing_Show
    get("/writing/:path_id",{ :controller => "application", :action => "writing_show" })

  # About
    get("/about",{ :controller => "application", :action => "about_index" })

  # Books
    get("/books",{ :controller => "application", :action => "books_index" })

  # Now
    get("/now",{ :controller => "application", :action => "now_index" })
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  content    :string
#  title      :string
#  topic      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def writing_index
    matching_posts = Post.all
    @list_of_posts = matching_posts.order({ :created_at => :desc })
    render ({ :template => "writing_template/index.html.erb"})
  end

  def writing_show
    @the_title = params.fetch("path_id")
    @the_post = Post.where({ :title => @the_title }).at(0)

    render ({ :template => "writing_template/show.html.erb"})
  end

  def about_index
    render ({ :template => "about_template/index.html.erb"})
  end

  def books_index
    render ({ :template => "books_template/index.html.erb"})
  end

  def now_index
    render ({ :template => "now_template/index.html.erb"})
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    matching_posts = Post.all

    @list_of_posts = matching_posts.order({ :created_at => :desc })

    render({ :template => "posts/index.html.erb" })
  end

  def show
    the_id = params.fetch("path_id")

    matching_posts = Post.where({ :id => the_id })

    @the_post = matching_posts.at(0)

    render({ :template => "posts/show.html.erb" })
  end

  def create
    the_post = Post.new
    the_post.title = params.fetch("query_title")
    the_post.content = params.fetch("query_content")
    the_post.topic = params.fetch("query_topic")

    if the_post.valid?
      the_post.save
      redirect_to("/posts", { :notice => "Post created successfully." })
    else
      redirect_to("/posts", { :alert => the_post.errors.full_messages.to_sentence })
    end
  end

  def update
    the_id = params.fetch("path_id")
    the_post = Post.where({ :id => the_id }).at(0)

    the_post.title = params.fetch("query_title")
    the_post.content = params.fetch("query_content")
    the_post.topic = params.fetch("query_topic")

    if the_post.valid?
      the_post.save
      redirect_to("/posts/#{the_post.id}", { :notice => "Post updated successfully."} )
    else
      redirect_to("/posts/#{the_post.id}", { :alert => the_post.errors.full_messages.to_sentence })
    end
  end

  def destroy
    the_id = params.fetch("path_id")
    the_post = Post.where({ :id => the_id }).at(0)

    the_post.destroy

    redirect_to("/posts", { :notice => "Post deleted successfully."} )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about_template/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  
  <body>

  <div class="container">
        <p>Hi, I’m Nick. I’m an amateur writer and programmer.</p>
        <p>I've worn a few hats in my professional career. I got my start at a bulge bracket investment bank, cut my teeth as a debt & equity investor, and dabbled in early-stage venture capital. These days, I’m helping to build a supply chain startup focused on the forest products industry.</p>
        <p>I built Follow the Frigate to learn how to code. The site rests on the original code I wrote, but has morphed into a personal blog to share my learnings, reflections, and interests. Writing is largely a personal hobby, but I'm hoping to take the next step by publishing pieces in <s>the public eye</s> this quiet corner of the internet. I hope this site will serve as a tool to record and refine my thinking.</p>
        <p>"Follow the Frigate" is a tribute to the mighty <a target="_blank" href="https://www.allaboutbirds.org/guide/Magnificent_Frigatebird/overview#">frigatebird</a>. The frigatebird reminds me of where and how I grew up. More importantly, following the frigate is an analogy for living life and exploring interests. You can read more <a href="http://www.followfrigate.com/writing/On%20the%20Frigate">here</a>.</p>
        <hr>
        <p>I'd love to keep the dialogue going if something catches your eye. Thanks for reading. </p>
        <p>[xxx] -at- [xxx].com</p>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/books_template/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>

  <body>

    <div class="container">
      <p>A few of my favorites</p>

      <p>Non-fiction
        <ul>
          <li>Shoe Dog by Phil Knight</li>
          <li>Open by Andre Agassi</li>
          <li>The Way of Baseball by Shawn Green</li>
          <li>The Tender Bar by JR Moehringer</li>
          <li>Into Thin Air by John Krakauer</li>
          <li>Kitchen Confidential by Anthony Bourdain</li>
          <li>Railroader by Howard Green</li>
          <li>Red Notice by Bill Browder</li>
        </ul>
      </p> 
      <p>Fiction
        <ul>
          <li>A River Runs Through It by Norman Maclean</li>
          <li>Lonesome Dove by Larry McMurtry</li>
          <li>The Three Body Problem by Cixin Liu</li>
          <li>Last Days of Night by Graham Moore</li>
          <li>The Road by Cormac McCarthy</li>
          <li>The Old Man and the Sea by Ernest Hemingway</li>
        </ul>
      </p> 
      <p>Philosophy, Life, and Other
        <ul>
          <li>Zen and the Art of Motorcycle Maintenance by Robert M. Pirsig</li>
          <li>Thoughts of a Philosophical Fighter Pilot by James Stockdale</li>
          <li>Man's Search for Meaning by Viktor Frankl</li>
          <li>Draft No. 4 by John McPhee</li>
        </ul>
      </p>
      </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>
      Follow the Frigate
    </title>

    <!-- Expand the number of characters we can use in the document beyond basic ASCII 🎉 -->
    <meta charset="utf-8">

    <!-- Make it responsive to small screens. Include only if you're using responsive CSS. -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Helper methods that create <link>s and <script>s for all of the stylesheets and javascript files in the non-`/public/` assets folders. -->
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%# javascript_pack_tag  'application' %>

    <!-- Rendering a partial that has all the <link>s and <script>s for assets we are pulling from content-delivery networks. -->
    <%= render "shared/cdn_assets" %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <style>
      body { padding-bottom: 70px }

      /* not active */
      .nav-pills .nav-link:not(.active) {
        color: black;
      }

      /* active*/
      .nav-pills .nav-link {
        color: white;
      }
    </style>
</head>

<body>
  <%= render "shared/navbar" %>

  <div class="container">
    <div class="row">
      <div class ="col-2">
        <nav class="nav nav-pills flex-column flex-row">

          <a class="nav-link <%= 'active bg-dark' if current_page?(writing_path) || current_page?("/") %>" href="<%= writing_path %>">Writing</a>
          <a class="nav-link <%= 'active bg-dark' if current_page?(about_path) %>" href="<%= about_path %>">About</a>
          <a class="nav-link <%= 'active bg-dark' if current_page?(books_path) %>" href="<%= books_path %>">Books</a>
          <a class="nav-link <%= 'active bg-dark' if current_page?(now_path) %>" href="<%= now_path %>">Now</a>

          <!-- Old code that was keeping the dark pill on Writing -->
            <!--
              <a class="nav-link active bg-dark" aria-current="page" href="/writing">Writing</a>
              <a class="nav-link" href="/about">About</a>
              <a class="nav-link" href="/books">Books</a>
              <a class="nav-link" href="/now">Now</a> 
            -->

        </nav>
      </div>

      <div class ="col-10">

  <div class="container">
    <%= render "shared/flashes" %>

    <%= yield %>
  </div>

</body>
</html>

app/views/now_template/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>

  <body>

  <div class="container">
        <h3>What I'm doing now</h3>
          <h5>Where:</h5>
            <p>Chicago! Living in the Windy City is great, except when it's windy. There’s no shortage of things to do, friends to see, and areas to explore.</p>
          <h5>What:</h5>
            <p>Building, making mistakes, and learning. In that order.</p> 
          <h5>Next:</h5>
            <p>Not sure!</p>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/posts/index.html.erb
<div>
  <div>
    <h1>
      List of all posts
    </h1>
  </div>
</div>

<hr>

<div>
  <div>
    <h2>
      Add a new post
    </h2>

    <form action="/insert_post" method="post">
      <div>
        <label for="title_box">
          Title
        </label>

        <input type="text" id="title_box" name="query_title">
      </div>

      <div>
        <label for="content_box">
          Content
        </label>

        <input type="text" id="content_box" name="query_content">
      </div>

      <div>
        <label for="topic_box">
          Topic
        </label>

        <input type="text" id="topic_box" name="query_topic">
      </div>

      <button>
        Create post
      </button>
    </form>
  </div>
</div>

<hr>
<div>
  <div>
    <table border="1">
      <tr>
        <th>
          ID
        </th>

        <th>
          Title
        </th>

        <th>
          Content
        </th>

        <th>
          Topic
        </th>

        <th>
          Created at
        </th>

        <th>
          Updated at
        </th>

        <th>
        </th>
      </tr>

      <% @list_of_posts.each do |a_post| %>
      <tr>
        <td>
          <%= a_post.id %>
        </td>

        <td>
          <%= a_post.title %>
        </td>

        <td>
          <%= a_post.content %>
        </td>

        <td>
          <%= a_post.topic %>
        </td>

        <td>
          <%= time_ago_in_words(a_post.created_at) %> ago
        </td>
        <td>
          <%= time_ago_in_words(a_post.updated_at) %> ago
        </td>

        <td>
          <a href="/posts/<%= a_post.id %>">
            Show details
          </a>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

<hr>

app/views/posts/show.html.erb
<div>
  <div>
    <h1>
      Post #<%= @the_post.id %> details
    </h1>

    <div>
      <div>
        <a href="/posts">
          Go back
        </a>
      </div>

      <div>
        <a href="/delete_post/<%= @the_post.id %>">
          Delete post
        </a>
      </div>
    </div>

    <dl>
      <dt>
        Title
      </dt>
      <dd>
        <%= @the_post.title %>
      </dd>

      <dt>
        Content
      </dt>
      <dd>
        <%= @the_post.content %>
      </dd>

      <dt>
        Topic
      </dt>
      <dd>
        <%= @the_post.topic %>
      </dd>

      <dt>
        Created at
      </dt>
      <dd>
        <%= time_ago_in_words(@the_post.created_at) %> ago
      </dd>

      <dt>
        Updated at
      </dt>
      <dd>
        <%= time_ago_in_words(@the_post.updated_at) %> ago
      </dd>
    </dl>
  </div>
</div>

<hr>


<div>
  <div>
    <h2>
      Edit post
    </h2>

    <form action="/modify_post/<%= @the_post.id %>"  method="post" >
      <div>
        <label for="title_box">
          Title
        </label>

        <input type="text" id="title_box" name="query_title" value="<%= @the_post.title %>">
      </div>

      <div>
        <label for="content_box">
          Content
        </label>

        <input type="text" id="content_box" name="query_content" value="<%= @the_post.content %>">
      </div>

      <div>
        <label for="topic_box">
          Topic
        </label>

        <input type="text" id="topic_box" name="query_topic" value="<%= @the_post.topic %>">
      </div>

      <button>
        Update post
      </button>
    </form>
  </div>
</div>

<hr>

app/views/shared/_cdn_assets.html.erb
<!-- Connect Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- Connect Font Awesome CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">

<!-- Connect Bootstrap JavaScript and its dependencies -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

<style>
  body {
    background-color: #FFF1E0
  }

    /* not active */
    .nav-pills .nav-link:not(.active) {
      color: black;
    }

    /* active*/
    .nav-pills .nav-link {
      color: white;
    }

</style>

app/views/shared/_flashes.html.erb
<div class="row">
  <div class="col-md-12">
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissable" role="alert">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-warning alert-dismissable" role="alert">
        <%= alert %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light mb-4">
  <div class="container">
    <a class="navbar-brand" href="/">
      Follow the Frigate
    </a>
  </div> <!-- .container -->
</nav>

app/views/shared/_panel.html.erb
<nav class="navbar">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsible-nav-links" aria-controls="collapsible-nav-links" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="container">
    <div class="row">
        <nav class="nav flex-column nav-pills">
          <a class="nav-link active bg-dark" aria-current="page" href="/writing">Writing</a>
          <a class="nav-link" aria-current="page" href="/writing">Writing</a>
        </nav>  
    </div>
  </div> <!-- .navbar-collapse -->
</nav>

app/views/writing_template/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>

  <body>

      <div class="container">
        <p>Hi, I'm Nick. Currently writing, reading, and learning about the world.</p>
          
        <!-- Table item-->
          <div class="container">
            <div class="row justify-content-between">

              <table width="100%" border ="0">
                <% @list_of_posts.each do |post| %>

                  <tr>
                    <td>
                      <div class="col">
                        <a href="/writing/<%= post.title %>">
                          <%= post.title %>
                      </div>
                    </td>
                
                    <td text-align="center">
                      <div class="col">
                        <%= post.created_at.strftime("%B %e, %Y") %>
                      </div>
                    </td>
                  </tr>

                <% end %>
              </table>
      </div>
      </div>
      </div>

      </div>
    </div>
  </div>

  </body>
</html>

app/views/writing_template/show.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  
  <body>

  <div class="container">
        <h3> <%= @the_post.title %> </h3>
        <p> <%= simple_format @the_post.content %> </p>
        <p> Written on <%= @the_post.created_at.strftime("%B %e, %Y") %> </p>
      </div>
    </div>
  </div>

  </body>
</html>
      